name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,busybox:stable-glibc'  # 设置默认的 Docker 镜像列表
      artifact_name:
        description: '请填写制品包名称'
        required: true
        default: 'artifact'  # 设置制品包名称
      
      

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04
    outputs:
      # 显式声明工件为公开
      public_artifacts: true  # 整个 Job 的输出工件设为公开

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          for image in "${image_array[@]}"; do
            docker pull "${image}" --platform "linux/amd64"
            image_name="${image//\//_}"
            image_name="${image_name//:/_}"
            docker save "${image}" -o "${image_name}-amd64.tar"
            gzip -c "${image_name}-amd64.tar" > "${image_name}-amd64.tar.gz"
            curl -T ${image_name}-amd64.tar.gz chenxiang-public.oss-cn-shanghai.aliyuncs.com/docker-images/
            rm "${image_name}-amd64.tar"
          done

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.artifact_name }}
        path: ${{ github.workspace }}/*.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

